project:
  type: website

website:
  title: "A Rogue Historian"
  navbar:
    title: "Jesse Sadler"
    right:
      - about.qmd
      - icon: github
        href: https://github.com/jessesadler
      - icon: twitter
        href: https://twitter.com/vivalosburros
format:
  html:
    theme: litera
    css: styles.css



