project:
  type: website

website:
  title: "A Rogue Historian"
  favicon: favicon.ico
  navbar:
    title: "Jesse Sadler"
    background: "#ff9600"
    foreground: "#404040"
    pinned: true
    right:
      - file: project.qmd
      - file: course.qmd
      - text: "About"
        file: about.qmd
      - icon: github
        href: https://github.com/jessesadler
      - icon: twitter
        href: https://twitter.com/vivalosburros
format:
  html:
    theme: litera
    css: styles.css
    highlight-style: ayu
