---
title: "Talks"
---

An abbreviated list of recent talks that I have given on my historical research, Digital Humanities, and R. For a full list of talks, see [my CV](sadler-cv.pdf).

- "Rough Estimation: Inheritance, Accounting, and Sibling Rivalry in an Early Modern Merchant Family," Low Countries History Seminar, 15 October 2021
  - [Video](https://www.youtube.com/watch?v=qHTXnYiNC5c) and [Slides](slides/lchs2021.pdf)
- "Analyzing and Visualizing Double-Entry Bookkeeping: A Digital History Methodology," Renaissance Society of America, April 2021
	- [Slides](slides/rsa2021.pdf)
- "'How pleasant it is for brethren to dwell together in unity:' Family and Exile in the Dutch Revolt," 6–8 April 2021
- "Solving Niche Historical Problems with Digital Humanities," Cal State Chico Digital Humanities Series, 24 February 2021
- "vctrs: Creating custom vector classes with the vctrs package," RStudio Conference, 27–30 January 2020
	- [Video](https://resources.rstudio.com/rstudio-conf-2020/vctrs-creating-custom-vector-classes-with-the-vctrs-package-jesse-sadler) and [Slides](slides/RStudio2020.pdf)
- "Learning and Using the tidyverse for Historical Research," RStudio Conference, 15–18 January 2019
	- [Video](https://resources.rstudio.com/rstudio-conf-2019/learning-and-using-the-tidyverse-for-historical-research) and [Slides](slides/RStudio2019.pdf)
- "Coding for the Humanities," Workshop funded by the Mellon Scholars Program at Hope College, 16 November 2018
	- [Slides and code](https://github.com/jessesadler/hope-intro2r)
