---
title: "New kinds of Projects: DH 2.0 and Coding"
description: "Moving from organizing research to creating Digital Humanities Projects, or why I decided to learn R"
date: "2017-08-16"
categories: ["digitalhumanities"]
---

In the process of learning about how I could use digital technologies to better organize my research, I quickly started to think about how I might extend these skills to produce new kinds of outputs.[^1] I was familiar with the concept of digital humanities, but the step from an internal process of organizing research and writing to production seemed both too nebulous and difficult. Digital humanities also seemed to concentrate on the visual. This was intriguing, but did not present itself as the most pressing need for a graduate student who was writing a dissertation on sibling relations among 16th-century merchants. It took years for me to move from what I am calling DH 1.0 to DH 2.0, to move from research methodology to making what could properly be termed digital humanities projects. This post presents an introduction to how I eventually took this step and why I decided to learn to code instead of other available solutions.[^2]

In reading tech websites and listening to tech podcasts I inevitably came into contact with the question of how to learn to program. A refrain that I heard over and over was that it was best to have a project in mind. Programming, I was told, is not an abstract entity, but something that one does to complete a set of specific tasks. In one sense this advice was encouraging. I had a possible digital humanities project in mind. I wanted to map a correspondence network of the letters found in the [archive of Daniel van der Meulen](https://www.erfgoedleiden.nl/collecties/archieven/archievenoverzicht/ead/index/zoekterm/meulen/eadid/0096). The archive contains approximately 6,600 letters that Daniel received from 1578 to 1600. A chapter of my dissertation analyzes the collection, but the work was all done by hand in spreadsheets. When it came time to visualize the data, I was not able to find the time or energy to do more than make rather simplistic maps on a website and creating some graphs with Numbers. This sufficed for the purposes of the dissertation, but it did not bring me any closer to digital humanities. Alongside the issue of time, I simply did not know what a solution could look like with more sophisticated tools much less with code. Working with data in code seemed interesting and powerful, but I had difficulty moving beyond my naive ideas about coding and digital humanities where there appeared endless possibilities but concrete steps were mysterious and nebulous.[^3]

At the [American Historical Association’s](http://historians.org) annual meeting in Denver in January of this year I was inspired by a number panels on the use of digital humanities in History, especially by [Henry Lovejoy’s](http://www.colorado.edu/history/henry-lovejoy) [Liberated Africans Project](http://www.liberatedafricans.org) and [Kate Craig’s](https://cla.auburn.edu/history/people/faculty/kate-craig/) discussion of using digital humanities in the classroom.[^4] These panels motivated me to finally take the initiative to learn more about the tools of digital humanities and think about how I could create a project analyzing and visualizing the correspondence network of Daniel van der Meulen. I started by gathering together information on digital humanities in general. I found a plethora of sources such as [AHA’s Digital History Resources](https://www.historians.org/teaching-and-learning/digital-history-resources), [DH Toychest](http://dhresourcesforprojectbuilding.pbworks.com/w/page/69244243/FrontPage), [Digital Humanities Now](http://digitalhumanitiesnow.org), and [The Programming Historian](http://programminghistorian.org). Most helpful in the early going was reading through [Johanna Drucker’s *Introduction to Digital Humanities Course Book: Concepts, Methods, and Tutorials for Students and Instructors*](https://www.scribd.com/document/345432425/Introduction-to-Digital-Humanities-Johanna-Drucker). This book is based on the Digital Humanities 101 course at UCLA and covers topics from HTML to textual analysis. Most interesting for me were the sections on networks and GIS or Geographical Information Systems.

My initial research gave me a starting point, but now I actually had to choose a path forward and decide on a tool or set of tools to create the project. I began by playing around with [Tableau Public](https://public.tableau.com) and [Palladio](http://hdlab.stanford.edu/palladio/). Both provide more or less ready-made visualizations of spreadsheet data, the former as a desktop application and the latter as a web app. Both were interesting, but they lacked in terms of customization and did little to help me learn about producing visuals. I also tested out [Gephi](https://gephi.org), an open-source application for the visualization of networks. I went through [Martin Grandjean’s](http://www.martingrandjean.ch) very helpful [Introduction to Network Analysis and Visualization](http://www.martingrandjean.ch/gephi-introduction/). However, because my project was aimed at producing a geographic representation of a network, I gravitated towards [GIS tools](http://gisgeography.com/mapping-out-gis-software-landscape/). Initially, I was interested in [QGIS](http://www.qgis.org), an open-source GIS application popular among geographers, but I also kept thinking of the possibility of doing something completely different and trying to do the project with code. Having no experience with programming or code, I remained hesitant, but a couple of resources showed me that what I wanted to do was possible through code.

In getting a sense of digital humanities and digital history I came across the work of [Lincoln Mullen](http://lincolnmullen.com), a historian at George Mason. Lincoln has authored a number of digital history projects using the [programming language R](https://www.r-project.org). R was made by statisticians, but over the twenty years of its existence it has developed into a programming language fully capable of both data analysis and visualization. I read the Introduction to [Lincoln Mullen’s *Computational Historical Thinking: With Applications in R*](http://dh-r.lincolnmullen.com). The book is very much a work in progress, but the introduction was enough to convince me that I could accomplish my goals with R. Further exploring resources on R, I came across [Taylor Arnold and Lauren Tilton’s *Humanities Data in R: Exploring Networks, Geospatial Data, Images, and Text*](http://www.springer.com/us/book/9783319207018).[^5] This book put all my reservations about learning to code and the possibilities of using R to rest. I was convinced that I needed to dive all the way in and learn R. I knew that it would not be the easiest way to produce a visualization of a correspondence network, but I also began to realize the actual potential of code.

[^1]:	For more on how I got interested in digital technologies see the below post [Thinking about Workflow: DH 1.0](https://jessesadler.com/post/thinking-about-workflow/)

[^2]:	In this post I am using both coding and programming in a colloquial manner. By both terms I simply mean the creation of computer code to analyze and visualize data.

[^3]:	Taking a Digital Humanities course at UCLA was obviously an option, but, at least at the time, enrolling in a class never seemed particularly practical in the middle of writing my dissertation.

[^4]:	Both are former colleagues at UCLA.

[^5]:	You may be able to download a free copy of *Humanities Data in R* through your university.
